build: Separate lib_LTLIBRARIES initialization
Set lib_LTLIBRARIES with '=' to an empty value at the top of the
Makefile.am and append to it from the library-local block for
readability.

Here's the error you get if you don't set lib_LTLIBRARIES to be empty:

    error: lib_LTLIBRARIES must be set with '=' before using '+='

[META] In a subsequent commit, we're going to introduce a library and
       append it to lib_LTLIBRARIES in its local block, this makes
       things more readable.